# redis.conf
dir /data

# Bật AOF để đảm bảo dữ liệu không mất khi container restart
appendonly yes
appendfsync everysec

# Bảo mật: yêu cầu mật khẩu
user default off
user jiyuu on allkeys allchannels allcommands >a2amcpgo

# Giới hạn kết nối
maxclients 1000

# Giảm log không cần thiết
loglevel notice

# Giới hạn bộ nhớ (ví dụ 256MB)
maxmemory 256mb
maxmemory-policy allkeys-lru

# Bật bảo vệ (chống truy cập public)
protected-mode yes

# Chỉ bind cho container nội bộ
bind 0.0.0.0